In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns
%matplotlib inline

In [30]:
df = pd.read_csv("6-bank_customers.csv")

In [31]:
df.columns

Index(['age', 'job_satisfaction', 'balance', 'duration_last_call',
       'num_contacts_last_month', 'has_housing_loan', 'has_personal_loan',
       'communication_type', 'days_since_last_contact',
       'campaign_response_score', 'subscribed'],
      dtype='str')

In [32]:
df.head()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
0,-0.377957,1.043895,1.043494,-0.101838,-1.617442,0.402713,0.913601,-0.067192,0.175471,-1.049646,0
1,-0.325259,1.276263,-0.686123,-2.463205,-0.489426,-0.240715,-1.469496,1.006633,-0.833692,0.957744,0
2,0.739019,-0.600903,-0.177294,1.335714,-0.817332,-0.790047,1.457365,-0.218981,0.878643,-1.257740,0
3,0.474312,-1.103002,1.189936,-0.800186,0.912377,-0.406451,-1.130950,1.985111,1.379029,1.041768,1
4,0.927365,1.114796,0.080284,1.261064,0.761179,0.921563,0.440832,0.184645,-1.567739,-0.142107,1

In [33]:
df.describe()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.015084,0.031559,0.045069,-0.020771,0.016769,-0.042135,-0.025139,0.058969,-0.015637,0.022327,0.503000
std,1.021848,1.004281,1.006910,1.392738,1.268761,1.029279,1.267490,0.992629,1.000664,1.135131,0.500241
min,-3.718638,-3.116027,-3.534257,-4.999018,-2.587178,-3.250031,-4.932878,-3.187779,-2.819987,-2.071129,0.000000
25%,-0.685005,-0.657545,-0.647051,-1.057938,-0.981320,-0.722970,-0.855392,-0.598669,-0.693330,-1.050201,0.000000
50%,-0.030546,0.045869,0.040586,0.204506,-0.317137,-0.022343,0.148199,0.052208,0.018807,-0.037530,1.000000
75%,0.662124,0.701601,0.731615,1.061181,1.017388,0.596557,1.020255,0.722446,0.641338,0.760782,1.000000
max,2.765266,2.658705,3.357941,3.477210,3.954873,3.206344,2.343380,3.600187,3.477044,4.124285,1.000000

In [34]:
X = df.drop("subscribed",axis=1)
y = df["subscribed"]

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 15)

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
y_pred = logistic.predict(X_test)

In [38]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [40]:
score = accuracy_score(y_test,y_pred)
print("score: ",score)
print("classification report: \n" ,classification_report(y_test,y_pred))
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))

score:  0.92
classification report:
               precision    recall  f1-score   support

           0       0.91      0.92      0.92       145
           1       0.93      0.92      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion matrix:
 [[134  11]
 [ 13 142]]

In [41]:
#hyperparameter tuning

In [42]:
model = LogisticRegression()

In [43]:
penalty = ["l1","l2","elasticnet"]
c_values = [100,10,1,0.1,0.01]
solver = ["newton-cg","liblinear","sag","saga","lbfgs","newton-cholesky"]

In [44]:
params =dict(penalty=penalty,C=c_values,solver=solver)

In [45]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton-cg',
  'liblinear',
  'sag',
  'saga',
  'lbfgs',
  'newton-cholesky']}

In [46]:
#grid search cv

In [55]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [56]:

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [57]:
grid = GridSearchCV(estimator=model,param_grid=params,cv=cv,scoring="accuracy",n_jobs=-1)

In [58]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'liblinear', 'sag', 'saga',
                                    'lbfgs', 'newton-cholesky']},
             scoring='accuracy')

In [60]:
grid.fit(X_train,y_train)

C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
225 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 91, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.91714286        nan 0.91714286        nan        nan
 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286
        nan        nan        nan 0.91714286        nan        nan
        nan 0.91857143        nan 0.91857143        nan        nan
 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286
        nan        nan        nan 0.91714286        nan        nan
        nan 0.91857143        nan 0.91857143        nan        nan
 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286
        nan        nan        nan 0.91714286        nan        nan
        nan 0.92142857        nan 0.92142857        nan        nan
 0.91714286 0.92285714 0.91714286 0.91714286 0.91714286 0.91714286
        nan        nan        nan 0.91714286        nan        nan
        nan 0.92142857        nan 0.92142857        nan        nan
 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286 0.91714286
        nan        nan        nan 0.91714286        nan        nan]
  warnings.warn(
C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'liblinear', 'sag', 'saga',
                                    'lbfgs', 'newton-cholesky']},
             scoring='accuracy')

In [62]:
print("En iyi parametreler:", grid.best_params_)
print("En iyi CV accuracy:", grid.best_score_)

En iyi parametreler: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
En iyi CV accuracy: 0.9228571428571428

In [63]:
best_model = grid.best_estimator_

y_pred_grid = best_model.predict(X_test)

print("Test accuracy:", accuracy_score(y_test, y_pred_grid))
print(classification_report(y_test, y_pred_grid))
print(confusion_matrix(y_test, y_pred_grid))

Test accuracy: 0.9233333333333333
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.95      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[137   8]
 [ 15 140]]

In [64]:
#random search cv

In [65]:
from sklearn.model_selection import RandomizedSearchCV

In [66]:
model = LogisticRegression()

In [68]:
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,n_iter=10,scoring="accuracy",n_jobs=-1)

In [69]:
randomcv.fit(X_train,y_train)

C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 91, in _check_solver
    raise ValueError(
        f"Only 'saga' solver supports elasticnet penalty, got solver={solver}."
    )
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1416, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 83, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.92              nan 0.91571429        nan        nan
        nan 0.92       0.91571429 0.92      ]
  warnings.warn(
C:\Users\busra\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'liblinear',
                                                   'sag', 'saga', 'lbfgs',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [70]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 1}

In [71]:
randomcv.best_score_

np.float64(0.9199999999999999)

In [72]:
y_pred_random = randomcv.predict(X_test)

print("Test accuracy:", accuracy_score(y_test, y_pred_random))
print(classification_report(y_test, y_pred_random))
print(confusion_matrix(y_test, y_pred_random))

Test accuracy: 0.92
              precision    recall  f1-score   support

           0       0.91      0.92      0.92       145
           1       0.93      0.92      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[134  11]
 [ 13 142]]